carts/urls.py
from django.conf.urls import url

from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done
)

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/', checkout_done, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.conf.urls import url, include
from django.views.generic import TemplateView
from carts.views import cart_detail_api_view
from billing.views import  payment_method_view, payment_method_createview
from accounts.views import (#login_page,
                             #register_page, 
                             LoginView,
                             RegisterView,
                             guest_register_view)
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .views import (home_page, 
                    about_page, 
                    contact_page , 
                    #login_page, 
                    #regist
                    #er_page
                    )
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView

""" from products.views import ( ProductListView, 
                             Product_list_view, 
                             ProductDetailView,
                             ProductDetailSlugView, 
                             Product_detail_view,
                             ProductFeaturedListView,
                             ProductFeaturedDetailView,
                            ) """
urlpatterns = [
    url(r'^$', home_page, name="home"),
    url(r'^about/$', about_page, name="about"),
    url(r'^contact/$',contact_page, name="contact"),
    #url(r'^login/$', login_page, name="login"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^api/cart/$', cart_detail_api_view, name="api-cart"),
    #url(r'^register/$', register_page, name="register"),
    url(r'^register/$', RegisterView.as_view( ), name="register"),
    url(r'^checkout/address/create/$', checkout_address_create_view, name="checkout_address_create"),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name="checkout_address_reuse"),
    url(r'^register/guest/$', guest_register_view, name="guest_register"),
    url(r'^bootstrap/$', TemplateView.as_view(template_name="bootstrap/justExample.html")),
    url(r'^products/', include(("products.urls", 'products'), namespace='products')),
    url(r'^cart/', include(("carts.urls", 'cart'), namespace='cart')),
    url(r'^billing/payment-method/$', payment_method_view, name="billing-payment-method"),
    url(r'^billing/payment-method/create/$', payment_method_createview, name="billing-payment-method-endpoint"),
    url(r'^search/', include(("search.urls", 'search'), namespace='search')),
    url(r'^settings/email/', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^webhooks/mailchimp/', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    #url(r'^featured/$', ProductFeaturedListView.as_view()),
    #url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
    #url(r'^products/$', ProductListView.as_view()),
    #url(r'^products-fbv/$', Product_list_view),
    #url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
    #url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
    #url(r'^products-fbv/(?P<pk>\d+)/$', Product_detail_view),
    url(r'admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path
from django.conf.urls import url, include


from .views import         ( 
                            ProductListView, 
                            #Product_list_view, 
                            #ProductDetailView,
                            ProductDetailSlugView, 
                            #Product_detail_view,
                            #ProductFeaturedListView,
                            #ProductFeaturedDetailView,
                            )
urlpatterns = [
    url(r'^$', ProductListView.as_view(), name="list"),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]

templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<!-- FontAwesome  
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />-->
<!-- <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
 -->
 <link rel='stylesheet' href='https://cdn.bootcss.com/font-awesome/5.12.1/css/all.css' />

<!-- jquery confirm css  -->
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">


 <!-- Stripe styling css  -->
 <link rel="stylesheet" href="{% static 'css/stripe-styling.css' %}">

templates/base/forms.html
{% extends 'base.html' %}
{% block content %}
<div class="col-12 col-md-6 mx-auto">
 {% if title %}   <h1 class="my-3">{{title}}</h1>{% endif %}
<form method='POST' action="{% if action_url %}{{action_url}}{% endif %}">{% csrf_token %}
{% if next_url %}
<input type="hidden" name="next" value="{{next_url}}"/>
{% endif %}
{{form.as_p}}
<button type="submit" class="btn btn-info">save</button>
</form>
</div>
{% endblock %}

templates/base/js.html
{% load static %}
<!-- slim is missing Ajax -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<!-- slim is missing Ajax -->
<!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
 -->

<!-- Stripe JS -->
<script src="https://js.stripe.com/v3/"></script>

<!-- jquery confirm js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

<!-- JS Render -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/1.0.6/jsrender.min.js"></script>
{% include 'base/js_template.html' %}

<!-- Django secure Ajax js -->
<script src="{% static 'js/csrf.ajax.js' %}"></script>

<!-- eCommerce custom JS with Jquery -->
<script src='{% static "js/ecommerce.js" %}'></script>

<!-- eCommerce main JS -->
<script src='{% static "js/ecommerce.main.js" %}'></script>

templates/base/js_template.html
{% verbatim %}
<!-- Stripe template Form -->
<script id="stripeTemplate" type="text/x-jsrender" >
  <form class="payment-form" action="" method="post" 
  id="payment-form" data-token="{{:publishKey}}" data-next-url='{{:nextUrl}}'>
    <div class="form-row">
      <label for="card-element">
        Credit or debit card
      </label>
      <div id="card-element" class="form-control">
        <!-- A Stripe Element will be inserted here. -->
      </div>
  
      <!-- Used to display form errors. -->
      <div id="card-errors" role="alert"></div>
    </div>
  
    <button class="btn btn-primary my-3 btn-load">{{:btnTitle}}</button>
  </form>
</script>
{% endverbatim %}

templates/base/nav.html
{% url 'products:list' as products_url %}
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'about' as about_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}



<nav class="navbar navbar-expand-lg navbar-dark bg-info">
  <div class="container">
    <a class="navbar-brand" href="#">
      <img src="http://getbootstrap.com/docs/4.4/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
      {{brand_name}}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.path == home_url %} active {% endif %}">
            <a class="nav-link" href="{{home_url}}">Home</a>
        </li>
        <li class="nav-item {% if request.path == products_url%} active {% endif %}">
            <a class="nav-link" href="{{products_url}}">Products</a>
        </li>
        <li class="nav-item {% if request.path == about_url %} active {% endif %}">
            <a class="nav-link" href="{{about_url}}">About</a>
        </li>
        <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
            <a class="nav-link" href="{{contact_url}}">Contact</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item {% if request.path == logout_url %} active {% endif %}">
            <a class="nav-link" href="{{logout_url}}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item {% if request.path == login_url %} active {% endif %}">
            <a class="nav-link" href="{{login_url}}">Login</a>
        </li>
        <li class="nav-item {% if request.path == register_url %} active {% endif %}">
            <a class="nav-link" href="{{register_url}}">Register</a>
        </li>
        {% endif %}
        <li class="nav-item {% if request.path == cart_url %} active {% endif %}">
          <a class="nav-link" href="{{cart_url}}"><span class="navbar_count">{{request.session.cart_items}}</span><i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
        </li>
        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{products_url}}">Products</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li> 
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>-->

      {% include 'search/snippets/search-form.html' %}
    </div>
  </div>
</nav>